<<<<<<< HEAD
services:
  - type: web
    name: investment-tracker-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && python app.py
    envVars:
      - key: PYTHON_VERSION
=======
services:
  - type: web
    name: investment-tracker-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && python app.py
    envVars:
      - key: PYTHON_VERSION
>>>>>>> 6217901f54d4a616e11e547dcf1f9cf5faa65607
        value: 3.11.0 